### ISSUE TITLE
JoinConference options startWithAudioMuted and startWithVideoMuted is not working on iOS

### ISSUE THREAD

**Issue by jefaokpta** [calvinckho/capacitor-jitsi-meet#66]
Hello everyone, first of all thanks by the plugin.

I made a MVP using the plugin and noted that this options (startWithAudioMuted and startWithVideoMuted) are not working on IOS. On Android it's ok.

`async join(url: string) {
    const roomName = url.substring(url.lastIndexOf('/') + 1);
    const config = await this.storage.get();
    if(!this.platform.is('hybrid')){
      console.log('not hybrid sala ' + roomName);
      console.log(config);
      return;
    }
    await Jitsi.joinConference({
      roomName, // room identifier for the conference
      url: 'https://meet.jit.si', // endpoint of the Jitsi Meet video bridge
      startWithAudioMuted: false, // start with audio muted
      startWithVideoMuted: true, // start with video muted
      displayName: config.name, // user's display name
      callIntegrationEnabled: false, // this.platform.is('ios'), // enable call integration (CallKit on iOS, ConnectionService on Android)
      token: null, // jwt authentication token
      email: null, // user's email
      avatarURL: null, // user's avatar url
      channelLastN: null, // last N participants allowed to join
      chatEnabled: true, // enable Chat feature
      inviteEnabled: false, // enable Invitation feature
    });
    // console.log('STATUS DE ENTRADA', result.success);

    window.addEventListener('onConferenceJoined', () => {
      console.log('ENTREI NA SALA');
    });
    window.addEventListener('onConferenceLeft', () => {
      console.log('SAIU DA SALA');
    });

    // const result: any = await Jitsi.leaveConference();
    // console.log("leave status": result.success);
  }`

Do i forget a thing?

Regards.

**Comment by calvinckho** [comment]
Thank you @jefaokpta for reporting this bug. I have fixed it and published a beta version. Please install 2.1.0-beta.2 and try again.

**Comment by jefaokpta** [comment]
Hi @calvinckho, i updated but still the same behavior 

<img width="664" alt="Screen Shot 2021-12-10 at 12 08 46" src="https://user-images.githubusercontent.com/10830832/145595962-bba4efbc-63e1-4716-8b23-58f8cb9c3c9d.png">

Android it's ok.

**Comment by calvinckho** [comment]
@jefaokpta did you do 'pod install --repo-update' in the ios folder, and then do 'npx cap update' in your project folder?

**Comment by calvinckho** [comment]
I tested on my app and it works.

**Comment by jefaokpta** [comment]
Thanks by hint, really worked. Just a detail, when i set startWithAudioMuted it mutes video too. Seems like startWithVideoMuted is no function.

**Comment by calvinckho** [comment]
Good catch, it was a typo in my code. I fixed it and released it as 2.1.0. Please install it and let me know if it works fine.

**Comment by jefaokpta** [comment]
Worked great! The most fast fix that i ever see! Congrats e thanks.

**Comment by calvinckho** [comment]
Awesome. Thanks again for your help for reporting and testing.

**Comment by calvinckho** [comment]
Sorry I really don't know why you can't see other participants. Maybe others have insights?

For detailed info about jwt tokens, see this issue: https://github.com/calvinckho/capacitor-jitsi-meet/issues/26
